In [166]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [167]:
movie_data  = pd.read_csv("Datas/5000_movies_bis.csv")
movie_data.head()

,color,director_name,num_critic_for_reviews,duration,director_fb_likes,actor_3_fb_likes,actor_2_name,actor_1_fb_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_fb_likes,imdb_score,aspect_ratio,movie_fb_likes
0,Color,James Cameron,723.00,178.00,0.00,855.00,Joel David Moore,1000.00,760505847.00,Action|Adventure|Fantasy|Sci-Fi,...,3054.00,English,USA,PG-13,237000000.00,2009.00,936.00,7.90,1.78,33000
1,Color,Gore Verbinski,302.00,169.00,563.00,1000.00,Orlando Bloom,40000.00,309404152.00,Action|Adventure|Fantasy,...,1238.00,English,USA,PG-13,300000000.00,2007.00,5000.00,7.10,2.35,0
2,Color,Sam Mendes,602.00,148.00,0.00,161.00,Rory Kinnear,11000.00,200074175.00,Action|Adventure|Thriller,...,994.00,English,UK,PG-13,245000000.00,2015.00,393.00,6.80,2.35,85000
3,Color,Christopher Nolan,813.00,164.00,22000.00,23000.00,Christian Bale,27000.00,448130642.00,Action|Thriller,...,2701.00,English,USA,PG-13,250000000.00,2012.00,23000.00,8.50,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.00,NaN,Rob Walker,131.00,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.00,7.10,NaN,0

In [168]:
movie_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   color                   5024 non-null   object
 1   director_name           4939 non-null   object
 2   num_critic_for_reviews  4993 non-null   float64
 3   duration                5028 non-null   float64
 4   director_fb_likes       4939 non-null   float64
 5   actor_3_fb_likes        5020 non-null   float64
 6   actor_2_name            5030 non-null   object
 7   actor_1_fb_likes        5036 non-null   float64
 8   gross                   4366 non-null   float64
 9   genres                  5043 non-null   object
 10  actor_1_name            5036 non-null   object
 11  movie_title             5043 non-null   object
 12  num_voted_users         5043 non-null   int64
 13  cast_total_fb_likes     5043 non-null   int64
 14  actor_3_name            5020 non-null   object
 15  facenumber_in_poster    5030 non-null   float64
 16  plot_keywords           4890 non-null   object
 17  movie_imdb_link         5043 non-null   object
 18  num_user_for_reviews    5022 non-null   float64
 19  language                5029 non-null   object
 20  country                 5038 non-null   object
 21  content_rating          4740 non-null   object
 22  budget                  4637 non-null   float64
 23  title_year              4935 non-null   float64
 24  actor_2_fb_likes        5030 non-null   float64
 25  imdb_score              5043 non-null   float64
 26  aspect_ratio            4714 non-null   float64
 27  movie_fb_likes          5043 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

In [169]:
movie_data.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_fb_likes', 'actor_3_fb_likes', 'actor_2_name',
       'actor_1_fb_likes', 'gross', 'genres', 'actor_1_name', 'movie_title',
       'num_voted_users', 'cast_total_fb_likes', 'actor_3_name',
       'facenumber_in_poster', 'plot_keywords', 'movie_imdb_link',
       'num_user_for_reviews', 'language', 'country', 'content_rating',
       'budget', 'title_year', 'actor_2_fb_likes', 'imdb_score',
       'aspect_ratio', 'movie_fb_likes'],
      dtype='object')

* afficher le nombre de valeurs nulles dans chaque colonne

In [170]:
for column in movie_data.columns:
    null_count = movie_data[column].isnull().sum()
    print(f"{column}: {null_count}")

color: 19
director_name: 104
num_critic_for_reviews: 50
duration: 15
director_fb_likes: 104
actor_3_fb_likes: 23
actor_2_name: 13
actor_1_fb_likes: 7
gross: 677
genres: 0
actor_1_name: 7
movie_title: 0
num_voted_users: 0
cast_total_fb_likes: 0
actor_3_name: 23
facenumber_in_poster: 13
plot_keywords: 153
movie_imdb_link: 0
num_user_for_reviews: 21
language: 14
country: 5
content_rating: 303
budget: 406
title_year: 108
actor_2_fb_likes: 13
imdb_score: 0
aspect_ratio: 329
movie_fb_likes: 0

valeurs manquantes colonne duraiton

In [171]:
# Calculez la moyenne des valeurs non manquantes dans la colonne "duration"
mean_duration = movie_data['duration'].mean()

# Remplacez les valeurs manquantes dans la colonne "duration" par la moyenne calculÃ©e
movie_data['duration'] = movie_data['duration'].fillna(mean_duration)

# VÃ©rifiez que les valeurs manquantes ont Ã©tÃ© remplacÃ©es
print(movie_data['duration'].isnull().sum())  # Doit renvoyer 0 si toutes les valeurs manquantes ont Ã©tÃ© remplacÃ©es

0

In [172]:
# Arrondir les valeurs de la colonne "duration" Ã  2 dÃ©cimales
movie_data['duration'] = movie_data['duration'].round(2)

In [173]:
movie_data.head()

,color,director_name,num_critic_for_reviews,duration,director_fb_likes,actor_3_fb_likes,actor_2_name,actor_1_fb_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_fb_likes,imdb_score,aspect_ratio,movie_fb_likes
0,Color,James Cameron,723.00,178.00,0.00,855.00,Joel David Moore,1000.00,760505847.00,Action|Adventure|Fantasy|Sci-Fi,...,3054.00,English,USA,PG-13,237000000.00,2009.00,936.00,7.90,1.78,33000
1,Color,Gore Verbinski,302.00,169.00,563.00,1000.00,Orlando Bloom,40000.00,309404152.00,Action|Adventure|Fantasy,...,1238.00,English,USA,PG-13,300000000.00,2007.00,5000.00,7.10,2.35,0
2,Color,Sam Mendes,602.00,148.00,0.00,161.00,Rory Kinnear,11000.00,200074175.00,Action|Adventure|Thriller,...,994.00,English,UK,PG-13,245000000.00,2015.00,393.00,6.80,2.35,85000
3,Color,Christopher Nolan,813.00,164.00,22000.00,23000.00,Christian Bale,27000.00,448130642.00,Action|Thriller,...,2701.00,English,USA,PG-13,250000000.00,2012.00,23000.00,8.50,2.35,164000
4,NaN,Doug Walker,NaN,107.20,131.00,NaN,Rob Walker,131.00,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.00,7.10,NaN,0

valeurs manquantes colonne language

In [174]:
# Filtrer les lignes oÃ¹ la valeur de la colonne "language" est NaN
movies_language_nan = movie_data.loc[movie_data['language'].isnull()]

# Afficher uniquement les noms des films oÃ¹ la valeur de la colonne "language" est NaN
print(movies_language_nan['movie_title'])

4       Star Wars: Episode VII - The Force AwakensÂ    ...
279                              10,000 B.C.Â
2459                           UnforgettableÂ
2895                                      Quest for FireÂ
3086                                      September DawnÂ
3539    Alpha and Omega 4: The Legend of the Saw Tooth...
3869                                        Silent MovieÂ
3931                                             SamsaraÂ
4110                                  Love's Abiding JoyÂ
4409                                Kickboxer: VengeanceÂ
4630                                         A Fine StepÂ
4810    Intolerance: Love's Struggle Throughout the AgesÂ
4885                                      The Big ParadeÂ
4958                      Over the Hill to the PoorhouseÂ
Name: movie_title, dtype: object

In [175]:
# Remplacer les valeurs NaN dans la colonne "language" lorsque le pays est "USA" par "English"
movie_data.loc[(movie_data['country'] == 'USA') & (movie_data.index != 3931), 'language'] = movie_data.loc[(movie_data['country'] == 'USA') & (movie_data.index != 3931), 'language'].fillna('English')

print(movie_data['language'].isnull().sum())  # Doit renvoyer 0 si toutes les valeurs manquantes ont Ã©tÃ© remplacÃ©es

4

In [176]:
# Afficher les lignes oÃ¹ 'language' est toujours NaN
nan_rows = movie_data[movie_data['language'].isna()]
result = nan_rows[['country', 'director_name', 'movie_title']]
print(result)

     country        director_name  \
4        NaN          Doug Walker
279      NaN  Christopher Barnard
2895  Canada  Jean-Jacques Annaud
3931     USA           Ron Fricke

                                            movie_title
4     Star Wars: Episode VII - The Force AwakensÂ    ...
279                            10,000 B.C.Â
2895                                    Quest for FireÂ
3931                                           SamsaraÂ

In [177]:
movie_data.loc[4, 'language'] = 'English'
movie_data.loc[2895, 'language'] = 'French'

In [178]:
movie_data['language'].isnull().sum()

2

valeurs manquantes country

In [179]:
nan_rows = movie_data[movie_data['country'].isna()]
result = nan_rows[[ 'director_name', 'movie_title', 'language']]
print(result)

            director_name                                        movie_title  \
4             Doug Walker  Star Wars: Episode VII - The Force AwakensÂ    ...
279   Christopher Barnard                           10,000 B.C.Â
2370                  NaN                      Gone, Baby, GoneÂ
3397                  NaN                              PreacherÂ
4021    Daniel Petrie Jr.                                       Dawn PatrolÂ

     language
4     English
279       NaN
2370  English
3397  English
4021  English

In [180]:
# Remplacer les valeurs NaN dans la colonne "language" lorsque le pays est "USA" par "English"
movie_data.loc[movie_data['language'] == 'English', 'country'] = movie_data.loc[movie_data['language'] == 'English', 'country'].fillna('USA')
print(movie_data['country'].isnull().sum())  # Doit renvoyer 0 si toutes les valeurs manquantes ont Ã©tÃ© remplacÃ©e

1

In [181]:
movie_data.loc[4, 'country'] = 'USA'
movie_data.loc[279, 'country'] = 'USA'

lignes dupliquÃ©es

In [182]:
# SÃ©lectionner les colonnes pertinentes
columns_to_check = ['director_name', 'actor_2_name', 'actor_1_name', 'actor_3_name', 'movie_title']

# VÃ©rifier les doublons sur ces colonnes
duplicate_rows = movie_data.duplicated(subset=columns_to_check, keep=False)

# Compter le nombre de lignes dupliquÃ©es
number_of_duplicate_rows = duplicate_rows.sum()

print("Nombre de lignes dupliquÃ©es sur les colonnes spÃ©cifiÃ©es:", number_of_duplicate_rows)

Nombre de lignes dupliquÃ©es sur les colonnes spÃ©cifiÃ©es: 239

In [183]:
# SÃ©lectionner les lignes dupliquÃ©es
duplicate_rows = movie_data[duplicate_rows]

# Compter le nombre de fois oÃ¹ chaque ligne dupliquÃ©e apparaÃ®t
duplicates_count = duplicate_rows.duplicated(subset=columns_to_check).value_counts()

print("Nombre de fois que chaque ligne unique dans les doublons se rÃ©pÃ¨te:")
print(duplicates_count)

Nombre de fois que chaque ligne unique dans les doublons se rÃ©pÃ¨te:
True     123
False    116
Name: count, dtype: int64

In [184]:
# Supprimer les doublons en se basant sur les colonnes spÃ©cifiÃ©es dans columns_to_check
movie_data.drop_duplicates(subset=columns_to_check, inplace=True)

# VÃ©rifier la forme du DataFrame aprÃ¨s suppression des doublons
print("Shape du DataFrame aprÃ¨s suppression des doublons:", movie_data.shape)

Shape du DataFrame aprÃ¨s suppression des doublons: (4920, 28)

In [185]:
# Supprimer les doublons en se basant sur les colonnes spÃ©cifiÃ©es dans columns_to_check
movie_data_unique = movie_data.drop_duplicates(subset=columns_to_check)

# VÃ©rifier la forme du DataFrame aprÃ¨s suppression des doublons
print("Shape du DataFrame aprÃ¨s suppression des doublons:", movie_data_unique.shape)

Shape du DataFrame aprÃ¨s suppression des doublons: (4920, 28)

In [186]:
# Compter le nombre de fois oÃ¹ chaque ligne unique dans les doublons se rÃ©pÃ¨te
duplicates_count_df = movie_data.duplicated(subset=columns_to_check).value_counts()

print("Nombre de fois que chaque ligne unique dans les doublons se rÃ©pÃ¨te:")
print(duplicates_count_df)

Nombre de fois que chaque ligne unique dans les doublons se rÃ©pÃ¨te:
False    4920
Name: count, dtype: int64

valeurs manquantes color

In [187]:

# Convertir la variable "color" en une variable binaire (0 pour noir et blanc, 1 pour couleur)
movie_data['color_binary'] = (movie_data['color'] == 'Color').astype(int)

# Calculer la corrÃ©lation entre la variable binaire "color_binary" et "title_year"
correlation = movie_data['color_binary'].corr(movie_data['title_year'])

print("CorrÃ©lation entre 'color' et 'title_year':", correlation)

CorrÃ©lation entre 'color' et 'title_year': 0.28934903563814773

In [188]:
# Filtrer les lignes oÃ¹ la valeur de la colonne "color" est NaN
movies_color_nan = movie_data.loc[movie_data['color'].isnull()]

# Afficher les movie_title et les movie_imdb_link de ces films
print(movies_color_nan[['movie_title', 'movie_imdb_link', 'title_year']])

                                            movie_title  \
4     Star Wars: Episode VII - The Force AwakensÂ    ...
279                            10,000 B.C.Â
459                              DaredevilÂ
1948                                         Dear JohnÂ
2015                                           Red SkyÂ
2459                         UnforgettableÂ
2753                                 Shinjuku IncidentÂ
3272                             Into the Grizzly MazeÂ
3539  Alpha and Omega 4: The Legend of the Saw Tooth...
3638                    Snow Flower and the Secret FanÂ
3656                                      Freaky DeakyÂ
4138                                  Something WickedÂ
4215                             The Rise of the KraysÂ
4331                                  Small ApartmentsÂ
4409                              Kickboxer: VengeanceÂ
4441                        Once Upon a Time in QueensÂ
4630                                       A Fine StepÂ
4846                                  Midnight CabaretÂ
5020                                        The RidgesÂ

                                        movie_imdb_link  title_year
4     http://www.imdb.com/title/tt5289954/?ref_=fn_t...         NaN
279   http://www.imdb.com/title/tt1869849/?ref_=fn_t...         NaN
459   http://www.imdb.com/title/tt3322312/?ref_=fn_t...         NaN
1948  http://www.imdb.com/title/tt0989757/?ref_=fn_t...     2010.00
2015  http://www.imdb.com/title/tt1946381/?ref_=fn_t...     2014.00
2459  http://www.imdb.com/title/tt1842530/?ref_=fn_t...         NaN
2753  http://www.imdb.com/title/tt1075419/?ref_=fn_t...     2009.00
3272  http://www.imdb.com/title/tt1694021/?ref_=fn_t...     2015.00
3539  http://www.imdb.com/title/tt4061848/?ref_=fn_t...     2014.00
3638  http://www.imdb.com/title/tt1541995/?ref_=fn_t...     2011.00
3656  http://www.imdb.com/title/tt0938305/?ref_=fn_t...     2012.00
4138  http://www.imdb.com/title/tt1327601/?ref_=fn_t...     2014.00
4215  http://www.imdb.com/title/tt2945796/?ref_=fn_t...     2015.00
4331  http://www.imdb.com/title/tt1272886/?ref_=fn_t...     2012.00
4409  http://www.imdb.com/title/tt3082898/?ref_=fn_t...     2016.00
4441  http://www.imdb.com/title/tt1639397/?ref_=fn_t...     2013.00
4630  http://www.imdb.com/title/tt1604100/?ref_=fn_t...     2014.00
4846  http://www.imdb.com/title/tt0100146/?ref_=fn_t...     1990.00
5020  http://www.imdb.com/title/tt1781935/?ref_=fn_t...     2011.00

In [189]:
# Remplacer toutes les valeurs NaN dans la colonne "color" par la chaÃ®ne de caractÃ¨res 'Color'
movie_data['color'] = movie_data['color'].fillna('Color')

# VÃ©rifier que les valeurs NaN ont Ã©tÃ© remplacÃ©es
print(movie_data['color'].isnull().sum())  # Doit renvoyer 0 si toutes les valeurs NaN ont Ã©tÃ© remplacÃ©es

0

valeurs manquantes gross  - mean

In [190]:
# Modifier les options d'affichage pour dÃ©sactiver la notation scientifique
pd.set_option('display.float_format', lambda x: '%.2f' % x)

# Calculez la moyenne des valeurs non manquantes dans la colonne "duration"

mean_duration = movie_data['gross'].mean()

# Remplacez les valeurs manquantes dans la colonne "duration" par la moyenne calculÃ©e
movie_data['gross'] = movie_data['gross'].fillna(mean_duration)

# VÃ©rifiez que les valeurs manquantes ont Ã©tÃ© remplacÃ©es
print(movie_data['gross'].isnull().sum())  # Doit renvoyer 0 si toutes les valeurs manquantes ont Ã©tÃ© remplacÃ©es

0

valeurs manquantes budget  - mean

In [191]:
# Calculez la moyenne des valeurs non manquantes dans la colonne "duration"

mean_duration = movie_data['budget'].mean()

# Remplacez les valeurs manquantes dans la colonne "duration" par la moyenne calculÃ©e
movie_data['budget'] = movie_data['budget'].fillna(mean_duration)

# VÃ©rifiez que les valeurs manquantes ont Ã©tÃ© remplacÃ©es
print(movie_data['budget'].isnull().sum())  # Doit renvoyer 0 si toutes les valeurs manquantes ont Ã©tÃ© remplacÃ©es

0

In [192]:
movie_data.budget

0      237000000.00
1      300000000.00
2      245000000.00
3      250000000.00
4       38921447.26
           ...
5038    38921447.26
5039    38921447.26
5040        1400.00
5041    38921447.26
5042        1100.00
Name: budget, Length: 4920, dtype: float64

NAN aspect_ratio

In [193]:
movie_data.aspect_ratio

0       1.78
1       2.35
2       2.35
3       2.35
4        NaN
        ...
5038     NaN
5039   16.00
5040     NaN
5041    2.35
5042    1.85
Name: aspect_ratio, Length: 4920, dtype: float64

valeurs manquantes facenumber

In [194]:
movie_data.facenumber_in_poster.unique()

array([ 0.,  1.,  4.,  3.,  2.,  6.,  7.,  5.,  8., nan, 10., 15.,  9.,
       11., 12., 31., 14., 19., 13., 43.])

In [195]:
# Filtrer les lignes oÃ¹ la valeur de la colonne "facenumber_in_poster" est NaN
movies_facenumber_nan = movie_data.loc[movie_data['facenumber_in_poster'].isnull()]

# Afficher les movie_imdb_link de ces films
print(movies_facenumber_nan['movie_imdb_link'])

99      http://www.imdb.com/title/tt0903624/?ref_=fn_t...
248     http://www.imdb.com/title/tt3949660/?ref_=fn_t...
1948    http://www.imdb.com/title/tt0989757/?ref_=fn_t...
3016    http://www.imdb.com/title/tt1929263/?ref_=fn_t...
3373    http://www.imdb.com/title/tt4254584/?ref_=fn_t...
3797    http://www.imdb.com/title/tt3567288/?ref_=fn_t...
3853    http://www.imdb.com/title/tt3014666/?ref_=fn_t...
4307    http://www.imdb.com/title/tt1390539/?ref_=fn_t...
4444    http://www.imdb.com/title/tt1105355/?ref_=fn_t...
4448    http://www.imdb.com/title/tt1236254/?ref_=fn_t...
4453    http://www.imdb.com/title/tt4063178/?ref_=fn_t...
4692    http://www.imdb.com/title/tt1015471/?ref_=fn_t...
5031    http://www.imdb.com/title/tt2049518/?ref_=fn_t...
Name: movie_imdb_link, dtype: object

In [196]:
# Remplacer la valeur NaN dans la colonne "facenumber_in_poster" Ã  l'index 99 par 1
movie_data.loc[99, 'facenumber_in_poster'] = 1
movie_data.loc[248, 'facenumber_in_poster'] = 4
movie_data.loc[1948, 'facenumber_in_poster'] = 2
movie_data.loc[3016, 'facenumber_in_poster'] = 1
movie_data.loc[3373, 'facenumber_in_poster'] = 2
movie_data.loc[3797, 'facenumber_in_poster'] = 2
movie_data.loc[3853, 'facenumber_in_poster'] = 6
movie_data.loc[4307, 'facenumber_in_poster'] = 7
movie_data.loc[4444, 'facenumber_in_poster'] = 4
movie_data.loc[4448, 'facenumber_in_poster'] = 1
movie_data.loc[4453, 'facenumber_in_poster'] = 1
movie_data.loc[4692, 'facenumber_in_poster'] = 4
movie_data.loc[5031, 'facenumber_in_poster'] = 8

Nan director name, actors

In [197]:
# Remplacer les NaN dans la colonne 'director_name' par 'Unknown'
movie_data['director_name'] = movie_data['director_name'].fillna('Unknown')
movie_data['actor_2_name'] = movie_data['actor_2_name'].fillna('Unknown')
movie_data['actor_1_name'] = movie_data['actor_1_name'].fillna('Unknown')
movie_data['actor_3_name'] = movie_data['actor_3_name'].fillna('Unknown')

drop lignes avec nan

In [198]:
# Supprimer toutes les lignes oÃ¹ 'num_user_for_reviews' est NaN
movie_data = movie_data.dropna(subset=['num_user_for_reviews'])

In [199]:
movie_data = movie_data.dropna(subset=['actor_1_fb_likes'])

In [200]:
movie_data.actor_1_fb_likes.isna().sum()

0

In [201]:
for column in movie_data.columns:
    null_count = movie_data[column].isnull().sum()
    print(f"{column}: {null_count}")

color: 0
director_name: 0
num_critic_for_reviews: 28
duration: 0
director_fb_likes: 100
actor_3_fb_likes: 13
actor_2_name: 0
actor_1_fb_likes: 0
gross: 0
genres: 0
actor_1_name: 0
movie_title: 0
num_voted_users: 0
cast_total_fb_likes: 0
actor_3_name: 0
facenumber_in_poster: 0
plot_keywords: 138
movie_imdb_link: 0
num_user_for_reviews: 0
language: 1
country: 0
content_rating: 280
budget: 0
title_year: 100
actor_2_fb_likes: 5
imdb_score: 0
aspect_ratio: 307
movie_fb_likes: 0
color_binary: 0

In [202]:
movie_data.genres.unique()

array(['Action|Adventure|Fantasy|Sci-Fi', 'Action|Adventure|Fantasy',
       'Action|Adventure|Thriller', 'Action|Thriller',
       'Action|Adventure|Sci-Fi', 'Action|Adventure|Romance',
       'Adventure|Animation|Comedy|Family|Fantasy|Musical|Romance',
       'Adventure|Family|Fantasy|Mystery', 'Action|Adventure',
       'Action|Adventure|Western', 'Action|Adventure|Family|Fantasy',
       'Action|Adventure|Comedy|Family|Fantasy|Sci-Fi',
       'Adventure|Fantasy', 'Action|Adventure|Drama|History',
       'Adventure|Family|Fantasy', 'Action|Adventure|Drama|Romance',
       'Drama|Romance', 'Action|Adventure|Sci-Fi|Thriller',
       'Action|Adventure|Fantasy|Romance',
       'Action|Adventure|Fantasy|Sci-Fi|Thriller',
       'Adventure|Animation|Comedy|Family|Fantasy',
       'Adventure|Animation|Comedy|Family|Sport', 'Action|Crime|Thriller',
       'Action|Adventure|Horror|Sci-Fi|Thriller',
       'Adventure|Animation|Family|Sci-Fi',
       'Action|Comedy|Crime|Thriller', 'Animation|Drama|Family|Fantasy',
       'Action|Crime|Drama|Thriller', 'Adventure|Animation|Comedy|Family',
       'Action|Adventure|Animation|Comedy|Family|Sci-Fi',
       'Adventure|Drama|Family|Mystery', 'Action|Comedy|Sci-Fi|Western',
       'Action|Adventure|Fantasy|Horror|Thriller',
       'Action|Adventure|Comedy|Sci-Fi', 'Comedy|Family|Fantasy',
       'Adventure|Animation|Comedy|Drama|Family|Fantasy',
       'Adventure|Drama|Family|Fantasy', 'Action|Adventure|Drama|Fantasy',
       'Action|Adventure|Family|Fantasy|Romance',
       'Action|Adventure|Drama|Sci-Fi', 'Action|Adventure|Romance|Sci-Fi',
       'Action|Adventure|Family|Mystery|Sci-Fi',
       'Action|Adventure|Animation|Comedy|Drama|Family|Sci-Fi',
       'Adventure|Animation|Comedy|Family|Sci-Fi',
       'Adventure|Animation|Family|Fantasy', 'Action|Sci-Fi',
       'Adventure|Drama|Sci-Fi', 'Action|Adventure|Drama|Horror|Sci-Fi',
       'Drama|Fantasy|Romance', 'Adventure|Sci-Fi',
       'Action|Adventure|Drama|Thriller',
       'Action|Drama|History|Romance|War',
       'Action|Adventure|Biography|Drama|History|Romance|War',
       'Action|Drama', 'Drama|Horror|Sci-Fi',
       'Adventure|Comedy|Family|Fantasy',
       'Animation|Comedy|Family|Fantasy',
       'Action|Adventure|Animation|Comedy|Family',
       'Adventure|Animation|Comedy|Family|Fantasy|Musical',
       'Mystery|Thriller', 'Adventure|Animation|Comedy|Drama|Family',
       'Action|Adventure|Animation|Comedy|Family|Fantasy|Sci-Fi',
       'Comedy|Fantasy|Horror', 'Drama|Fantasy|Horror|Thriller',
       'Action|Drama|Thriller', 'Adventure',
       'Action|Comedy|Fantasy|Sci-Fi',
       'Action|Adventure|Comedy|Family|Fantasy|Mystery|Sci-Fi',
       'Action|Adventure|Animation|Fantasy', 'Comedy|Crime',
       'Action|Drama|History|War', 'Action|Adventure|Drama',
       'Action|Adventure|Animation|Comedy|Family|Fantasy',
       'Action|Drama|Mystery|Sci-Fi', 'Action|Adventure|Comedy|Thriller',
       'Action|Adventure|Animation|Fantasy|Romance|Sci-Fi',
       'Action|Adventure|Drama|History|War',
       'Adventure|Drama|Fantasy|Romance',
       'Animation|Comedy|Family|Musical',
       'Action|Crime|Drama|Mystery|Thriller',
       'Adventure|Drama|Thriller|Western',
       'Adventure|Animation|Comedy|Family|Western',
       'Action|Mystery|Thriller', 'Adventure|Sci-Fi|Thriller',
       'Adventure|Animation|Comedy|Family|Fantasy|Sci-Fi',
       'Action|Crime|Mystery|Thriller', 'Action|Adventure|Family|Mystery',
       'Adventure|Drama|Romance|War',
       'Adventure|Animation|Family|Thriller', 'Action|Fantasy',
       'Action|Animation|Comedy|Family|Sci-Fi', 'Action|Comedy|Fantasy',
       'Fantasy', 'Adventure|Animation|Comedy|Family|Musical',
       'Action|Adventure|Crime|Mystery|Thriller',
       'Action|Adventure|History', 'Action', 'Adventure|Drama|Fantasy',
       'Action|Fantasy|Thriller', 'Action|Adventure|Comedy|Crime',
       'Adventure|Mystery|Sci-Fi', 'Action|Drama|Sci-Fi|Thriller',
       'Action|Crime|Sci-Fi|Thriller', 'Action|Family|Sport',
       'Comedy|Drama|Romance', 'Action|Comedy|Romance',
       'Action|Adventure|Mystery|Sci-Fi', 'Action|Drama|War',
       'Adventure|Drama|Sci-Fi|Thriller',
       'Action|Adventure|Comedy|Family|Fantasy', 'Crime|Thriller',
       'Action|Comedy|Crime|Romance|Thriller', 'Biography|Drama',
       'Action|Comedy|Crime|Sci-Fi|Thriller', 'Action|Adventure|Crime',
       'Action|Drama|Fantasy|War',
       'Animation|Comedy|Family|Music|Western',
       'Action|Adventure|Mystery|Sci-Fi|Thriller',
       'Action|Drama|Sci-Fi|Sport', 'Action|Crime|Romance|Thriller',
       'Action|Adventure|Comedy', 'Biography|Drama|Sport',
       'Action|Mystery|Sci-Fi|Thriller',
       'Animation|Family|Fantasy|Musical|Romance',
       'Action|Adventure|Romance|Sci-Fi|Thriller', 'Comedy|Romance',
       'Action|Drama|Romance', 'Biography|Crime|Drama|History|Romance',
       'Biography|Crime|Drama', 'Action|Comedy|Thriller',
       'Action|Comedy|Crime', 'Action|Drama|Mystery|Thriller',
       'Drama|Western', 'Animation|Drama|Family|Musical|Romance',
       'Action|Adventure|Comedy|Family|Mystery',
       'Action|Romance|Thriller', 'Action|Fantasy|Horror|Mystery',
       'Adventure|Drama|Thriller', 'Biography|Comedy|Crime|Drama',
       'Action|Sci-Fi|War', 'Drama|Sci-Fi',
       'Action|Adventure|Animation|Family|Fantasy',
       'Action|Crime|Fantasy|Romance|Thriller', 'Adventure|Comedy|Sci-Fi',
       'Action|Crime|Sport|Thriller',
       'Action|Adventure|Biography|Drama|History|Thriller',
       'Action|Comedy|Sci-Fi', 'Action|Drama|Thriller|War',
       'Drama|Mystery|Thriller', 'Action|Adventure|Fantasy|Thriller',
       'Crime|Drama', 'Drama|History|Romance|War',
       'Animation|Comedy|Family|Sport', 'Comedy|Sci-Fi|Thriller',
       'Drama|History|War', 'Comedy',
       'Adventure|Animation|Comedy|Family|Romance',
       'Drama|Family|Fantasy|Romance', 'Drama|Fantasy|Thriller',
       'Drama|Mystery|Romance|Sci-Fi|Thriller',
       'Drama|History|War|Western', 'Action|Adventure|Animation|Family',
       'Adventure|Comedy|Family|Mystery|Sci-Fi',
       'Drama|Fantasy|Horror|Mystery|Thriller',
       'Animation|Comedy|Family|Sci-Fi',
       'Adventure|Comedy|Drama|Fantasy|Romance',
       'Action|Adventure|Comedy|Crime|Thriller', 'Crime|Drama|Thriller',
       'Adventure|Animation|Family|Fantasy|Musical|War', 'Action|Comedy',
       'Crime|Drama|Mystery|Thriller', 'Adventure|Drama|History',
       'Action|Adventure|Animation|Family|Fantasy|Sci-Fi',
       'Adventure|Animation|Comedy|Family|Fantasy|Music',
       'Drama|History|Thriller|War', 'Action|Animation|Comedy|Sci-Fi',
       'Comedy|Family|Fantasy|Horror|Mystery',
       'Drama|Mystery|Sci-Fi|Thriller', 'Action|Horror|Sci-Fi|Thriller',
       'Crime|Mystery|Thriller',
       'Action|Adventure|Comedy|Crime|Mystery|Thriller',
       'Comedy|Drama|Sci-Fi', 'Action|Family|Fantasy|Musical',
       'Drama|History|Sport', 'Adventure|Drama|Romance',
       'Animation|Comedy|Family|Music|Romance',
       'Animation|Comedy|Family|Fantasy|Musical|Romance',
       'Crime|Drama|Horror|Mystery|Thriller', 'Adventure|Comedy|Family',
       'Action|Adventure|Comedy|Fantasy', 'Comedy|Drama|Music|Musical',
       'Adventure|Comedy|Drama|Family|Fantasy',
       'Action|Comedy|Fantasy|Romance', 'Comedy|Romance|Sci-Fi',
       'Adventure|Comedy|Mystery', 'Comedy|Drama|Fantasy|Romance',
       'Action|Comedy|Family|Fantasy',
       'Action|Adventure|Fantasy|Horror|Sci-Fi',
       'Crime|Drama|History|Mystery|Thriller', 'Comedy|Drama',
       'Adventure|Animation|Comedy|Drama|Family|Fantasy|Sci-Fi',
       'Action|Drama|Romance|Sci-Fi|Thriller', 'Comedy|Crime|Sport',
       'Comedy|Family|Fantasy|Romance',
       'Action|Adventure|Crime|Drama|Sci-Fi|Thriller',
       'Adventure|Drama|History|Romance|War', 'Comedy|Family|Sci-Fi',
       'Fantasy|Horror|Mystery|Thriller',
       'Adventure|Animation|Comedy|Family|Fantasy|Sci-Fi|Sport',
       'Adventure|Comedy|Crime|Family|Mystery', 'Drama|Sci-Fi|Thriller',
       'Action|Crime|Mystery|Romance|Thriller',
       'Action|Adventure|Comedy|Romance',
       'Adventure|Animation|Family|Western', 'Comedy|Family|Romance',
       'Action|Adventure|Family|Sci-Fi|Thriller',
       'Animation|Family|Fantasy|Music',
       'Action|Adventure|Family|Fantasy|Thriller', 'Comedy|Fantasy',
       'Action|Adventure|Comedy|Fantasy|Thriller',
       'Drama|Horror|Mystery|Sci-Fi', 'Action|Sci-Fi|Thriller',
       'Drama|History|Thriller', 'Adventure|Animation|Family',
       'Drama|Musical|Romance', 'Documentary|Drama',
       'Action|Adventure|Drama|History|Romance', 'Animation|Family',
       'Adventure|Animation|Drama|Family|Musical',
       'Animation|Comedy|Family|Fantasy|Sci-Fi',
       'Adventure|Animation|Drama|Family|Fantasy', 'Sci-Fi|Thriller',
       'Animation|Comedy|Family', 'Action|Crime|Fantasy|Thriller',
       'Comedy|Drama|Family|Music|Musical|Romance',
       'Horror|Mystery|Thriller', 'Action|Adventure|Comedy|Family|Sci-Fi',
       'Comedy|Family', 'Biography|Comedy|Drama|History',
       'Drama|Music|Musical', 'Crime|Drama|Mystery', 'Comedy|Crime|Music',
       'Action|Comedy|Romance|Thriller',
       'Animation|Comedy|Family|Fantasy|Mystery',
       'Comedy|Crime|Drama|Romance', 'Action|Adventure|Romance|Thriller',
       'Drama|History|Romance', 'Action|Drama|Fantasy|Romance',
       'Action|Adventure|Animation|Family|Sci-Fi', 'Action|Drama|Sci-Fi',
       'Drama|Horror|Sci-Fi|Thriller', 'Animation|Comedy|Fantasy',
       'Action|Animation|Comedy|Family',
       'Action|Adventure|Comedy|Romance|Thriller', 'Action|Comedy|Sport',
       'Biography|Drama|History|War', 'Adventure|Animation|Comedy',
       'Action|Drama|Sport', 'Adventure|Drama|Family',
       'Drama|Mystery|Romance|Thriller',
       'Adventure|Animation|Comedy|Family|Fantasy|Romance',
       'Adventure|Drama|War', 'Action|Adventure|Crime|Thriller',
       'Adventure|Drama|Fantasy|Mystery|Thriller',
       'Fantasy|Mystery|Romance|Sci-Fi|Thriller',
       'Drama|Fantasy|Mystery|Thriller',
       'Animation|Comedy|Family|Fantasy|Music',
       'Drama|Horror|Romance|Thriller', 'Drama|War', 'Drama',
       'Action|Drama|Fantasy|Horror|War',
       'Adventure|Family|Fantasy|Romance',
       'Adventure|Biography|Drama|History|War',
       'Action|Adventure|Horror|Sci-Fi', 'Action|Fantasy|Horror',
       'Comedy|Drama|Musical|Romance', 'Action|Sci-Fi|Sport',
       'Action|Adventure|Animation|Comedy|Crime|Family|Fantasy',
       'Adventure|Animation|Family|Fantasy|Musical',
       'Action|Crime|Mystery|Sci-Fi|Thriller',
       'Action|Comedy|Crime|Drama|Thriller',
       'Adventure|Drama|History|Romance', 'Biography|Drama|Thriller',
       'Action|Drama|History|Thriller', 'Action|Adventure|Fantasy|War',
       'Comedy|Fantasy|Romance',
       'Action|Adventure|Comedy|Romance|Thriller|Western',
       'Biography|Drama|Sport|War', 'Comedy|Drama|Family|Musical',
       'Action|Adventure|Fantasy|Horror|Sci-Fi|Thriller', 'Drama|Sport',
       'Action|Fantasy|Sci-Fi|Thriller', 'Drama|Mystery|Romance',
       'Adventure|Biography|Drama|History|Sport|Thriller',
       'Crime|Drama|Fantasy', 'Adventure|Biography|Crime|Drama|Western',
       'Action|War', 'Comedy|Romance|Sport',
       'Crime|Drama|Mystery|Thriller|Western', 'Comedy|Sport',
       'Comedy|Drama|Family', 'Crime|Drama|Fantasy|Mystery',
       'Adventure|Animation|Biography|Drama|Family|Fantasy|Musical',
       'Drama|Romance|Western', 'Documentary|Music', 'Drama|Thriller',
       'Animation|Family|Fantasy', 'Action|Fantasy|Horror|Sci-Fi',
       'Biography|Comedy|Drama', 'Action|Horror|Sci-Fi',
       'Adventure|Comedy', 'Biography|Drama|History|Sport',
       'Comedy|Crime|Romance|Thriller', 'Comedy|Crime|Romance',
       'Horror|Mystery|Sci-Fi|Thriller', 'Biography|Drama|Music',
       'Drama|Fantasy|Sport', 'Adventure|Comedy|Drama|Music',
       'Action|Fantasy|Horror|Sci-Fi|Thriller',
       'Adventure|Animation|Comedy|Drama|Family|Fantasy|Romance',
       'Horror|Sci-Fi|Thriller', 'Drama|Fantasy|Mystery|Romance|Thriller',
       'Action|Adventure|Drama|History|Romance|War',
       'Drama|Fantasy|Mystery|Romance', 'Fantasy|Horror|Mystery|Romance',
       'Adventure|Comedy|Family|Romance|Sci-Fi', 'Drama|Horror|Thriller',
       'Action|Comedy|Mystery|Romance',
       'Action|Adventure|Comedy|Romance|Sci-Fi',
       'Action|Biography|Drama|History|Thriller|War',
       'Adventure|Comedy|Family|Fantasy|Horror',
       'Comedy|Family|Romance|Sci-Fi', 'Action|Adventure|Thriller|War',
       'Comedy|Drama|Romance|Sport', 'Comedy|Western',
       'Action|Comedy|Crime|Drama', 'Drama|Music|Romance|War',
       'Action|Comedy|Drama|Family|Thriller', 'Action|Crime',
       'Adventure|Animation|Drama|Family|History|Musical|Romance',
       'Action|Adventure|Drama|Romance|Sci-Fi',
       'Action|Adventure|Comedy|Family|Romance',
       'Action|Adventure|Comedy|Western',
       'Biography|Drama|History|Musical',
       'Adventure|Drama|Horror|Thriller', 'Action|Drama|Sport|Thriller',
       'Drama|Musical|Romance|Thriller', 'Comedy|Drama|Family|Fantasy',
       'Adventure|Comedy|Crime|Family|Musical',
       'Drama|Music|Musical|Romance', 'Drama|Mystery|Romance|War',
       'Crime|Drama|Romance', 'Crime|Horror|Mystery|Thriller',
       'Adventure|Animation|Drama|Family|Fantasy|Musical|Mystery|Romance',
       'Action|Horror|Thriller', 'Drama|History|Horror',
       'Drama|Romance|Sport', 'Comedy|Family|Musical|Romance',
       'Romance|Sci-Fi|Thriller', 'Biography|Comedy|Drama|Romance',
       'Mystery|Sci-Fi|Thriller', 'Drama|Fantasy|Horror',
       'Adventure|Comedy|Drama|Fantasy|Musical', 'Horror|Mystery',
       'Action|Adventure|Family|Fantasy|Sci-Fi|Thriller',
       'Adventure|Comedy|Family|Fantasy|Romance|Sport',
       'Adventure|Horror|Mystery', 'Crime|Drama|Romance|Thriller',
       'Comedy|Crime|Drama|Thriller', 'Drama|Fantasy',
       'Adventure|Comedy|Drama', 'Action|Biography|Drama|History|War',
       'Adventure|Comedy|Fantasy', 'Adventure|Comedy|Crime|Drama|Family',
       'Action|Biography|Crime|Drama|Thriller', 'Comedy|Sci-Fi',
       'Drama|Romance|Sci-Fi',
       'Action|Adventure|Comedy|Crime|Music|Mystery',
       'Comedy|Drama|Music', 'Action|Crime|Drama|Sci-Fi|Thriller',
       'Horror|Thriller', 'Action|Adventure|Comedy|Drama|War',
       'Drama|Mystery|Sci-Fi', 'Crime|Drama|Music',
       'Adventure|Crime|Drama|Western', 'Comedy|Drama|Thriller',
       'Drama|Romance|War', 'Action|Comedy|Crime|Music|Romance|Thriller',
       'Crime|Romance|Thriller', 'Action|Adventure|Drama|Sci-Fi|Thriller',
       'Action|Drama|Fantasy|Thriller|Western',
       'Action|Drama|Mystery|Thriller|War',
       'Biography|Crime|Drama|Thriller', 'Action|Comedy|Crime|Romance',
       'Action|Adventure|Family|Fantasy|Sci-Fi',
       'Adventure|Comedy|Family|Musical', 'Action|Horror',
       'Action|Adventure|Horror|Thriller', 'Comedy|Drama|Music|Romance',
       'Action|Crime|Drama|Romance|Thriller',
       'Comedy|Family|Romance|Sport', 'Drama|Family|Fantasy',
       'Drama|Fantasy|Musical|Romance',
       'Adventure|Comedy|Family|Fantasy|Sci-Fi', 'Comedy|Musical',
       'Biography|Drama|History', 'Action|Crime|Drama|Thriller|War',
       'Comedy|Crime|Thriller', 'Drama|Fantasy|Horror|Mystery',
       'Action|Animation|Comedy|Family|Fantasy',
       'Biography|Drama|History|Thriller',
       'Action|Adventure|Crime|Drama|Mystery|Thriller',
       'Animation|Family|Fantasy|Musical', 'Adventure|Drama|Western',
       'Biography|Drama|History|Romance', 'Drama|Horror|Mystery|Thriller',
       'Action|Fantasy|Western', 'Comedy|War', 'Drama|Music',
       'Action|Drama|Family|Sport', 'Action|Biography|Drama|Thriller|War',
       'Comedy|Drama|Sport', 'Adventure|Comedy|Sci-Fi|Western',
       'Fantasy|Horror|Romance', 'Biography|Drama|Romance',
       'Action|Adventure|Drama|Romance|War',
       'Adventure|Comedy|Crime|Romance',
       'Comedy|Drama|Family|Fantasy|Romance', 'Horror', 'Comedy|Music',
       'Action|Adventure|Drama|Romance|Thriller',
       'Biography|Drama|Music|Musical', 'Drama|History',
       'Comedy|Music|Romance',
       'Action|Adventure|Crime|Fantasy|Mystery|Thriller',
       'Adventure|Drama|Mystery', 'Biography|Crime|Drama|Music',
       'Crime|Drama|Horror|Thriller',
       'Adventure|Animation|Comedy|Drama|Family|Fantasy|Musical',
       'Action|Adventure|Comedy|Music|Thriller',
       'Adventure|Animation|Comedy|Crime|Family',
       'Comedy|Romance|Sci-Fi|Thriller', 'Comedy|Crime|Family|Romance',
       'Crime|Horror|Thriller', 'Action|Horror|Mystery|Sci-Fi|Thriller',
       'Comedy|Fantasy|Sci-Fi',
       'Adventure|Animation|Comedy|Fantasy|Romance',
       'Action|Adventure|Family|Thriller',
       'Adventure|Comedy|Drama|Romance|Thriller|War',
       'Adventure|Animation|Comedy|Fantasy|Music|Romance',
       'Action|Drama|Fantasy', 'Action|Adventure|Drama|Fantasy|War',
       'Drama|Fantasy|Romance|Sci-Fi',
       'Animation|Comedy|Family|Horror|Sci-Fi',
       'Biography|Drama|Romance|Sport', 'Action|Biography|Drama',
       'Adventure|Drama', 'Horror|Mystery|Sci-Fi',
       'Action|Adventure|Drama|Thriller|Western',
       'Adventure|Family|Fantasy|Sci-Fi',
       'Adventure|Comedy|History|Romance', 'Action|Biography|Drama|Sport',
       'Drama|Family',
       'Action|Adventure|Crime|Drama|Family|Fantasy|Romance|Thriller',
       'Biography|Comedy|Romance', 'Action|Biography|Drama|History',
       'Biography|Drama|War', 'Adventure|Comedy|Family|Sci-Fi',
       'Biography|Drama|Family|History|Sport',
       'Biography|Comedy|Drama|History|Music', 'Fantasy|Horror',
       'Comedy|Drama|Family|Sport', 'Comedy|Drama|Romance|Sci-Fi',
       'Adventure|Animation|Comedy|Family|War',
       'Action|Comedy|Sci-Fi|Thriller', 'Comedy|Horror',
       'Drama|Thriller|War', 'Action|Western',
       'Action|Adventure|Family|Sci-Fi',
       'Adventure|Biography|Drama|Thriller', 'Drama|Romance|War|Western',
       'Action|Comedy|Crime|Western',
       'Action|Adventure|Comedy|Drama|Thriller', 'Drama|Music|Romance',
       'Action|Adventure|Crime|Drama|Thriller',
       'Adventure|Comedy|Family|Sport', 'Comedy|Drama|Fantasy',
       'Comedy|Family|Sport', 'Action|Adventure|Drama|Family',
       'Action|Comedy|War', 'Drama|Family|Sport',
       'Action|Thriller|Western', 'Action|Drama|Fantasy|Horror|Thriller',
       'Animation|Comedy|Family|Fantasy|Musical',
       'Action|Adventure|Comedy|Fantasy|Romance',
       'Action|Crime|Drama|Mystery|Sci-Fi|Thriller',
       'Adventure|Comedy|Crime|Drama', 'Drama|Mystery',
       'Comedy|Fantasy|Horror|Thriller',
       'Crime|Drama|Mystery|Sci-Fi|Thriller', 'Comedy|Crime|Musical',
       'Comedy|Drama|Family|Music|Romance', 'Comedy|Horror|Romance',
       'Comedy|Family|Fantasy|Sport',
       'Animation|Comedy|Family|Mystery|Sci-Fi',
       'Adventure|Comedy|Drama|Family|Sport',
       'Animation|Drama|Family|Fantasy|Musical|Romance',
       'Comedy|Horror|Musical|Sci-Fi', 'Crime|Drama|Sport',
       'Action|Adventure|Animation|Drama|Mystery|Sci-Fi|Thriller',
       'Action|Adventure|Crime|Drama|Romance', 'Action|Comedy|Horror',
       'Adventure|Horror|Thriller', 'Adventure|Fantasy|Mystery',
       'Action|Drama|Romance|Sport',
       'Biography|Crime|Drama|History|Western',
       'Action|Biography|Crime|Drama', 'Adventure|Animation|Fantasy',
       'Adventure|Animation|Comedy|Fantasy',
       'Biography|Drama|Music|Romance',
       'Adventure|Drama|Mystery|Sci-Fi|Thriller',
       'Biography|Comedy|Crime|Drama|Romance|Thriller',
       'Biography|Crime|Drama|History|Music',
       'Adventure|Animation|Comedy|Drama|Family|Musical',
       'Biography|Comedy|Drama|Music|Romance',
       'Adventure|Animation|Sci-Fi', 'Drama|Romance|Thriller',
       'Action|Fantasy|Horror|Thriller', 'Adventure|Biography',
       'Documentary', 'Action|Comedy|Family', 'Action|Horror|Romance',
       'Adventure|Drama|History|Romance|Thriller|War',

In [203]:
movie_data = movie_data.dropna(subset=['director_fb_likes'])

In [204]:
movie_data = movie_data.dropna(subset=['num_critic_for_reviews'])

In [205]:
for column in movie_data.columns:
    null_count = movie_data[column].isnull().sum()
    print(f"{column}: {null_count}")

color: 0
director_name: 0
num_critic_for_reviews: 0
duration: 0
director_fb_likes: 0
actor_3_fb_likes: 10
actor_2_name: 0
actor_1_fb_likes: 0
gross: 0
genres: 0
actor_1_name: 0
movie_title: 0
num_voted_users: 0
cast_total_fb_likes: 0
actor_3_name: 0
facenumber_in_poster: 0
plot_keywords: 121
movie_imdb_link: 0
num_user_for_reviews: 0
language: 1
country: 0
content_rating: 233
budget: 0
title_year: 0
actor_2_fb_likes: 3
imdb_score: 0
aspect_ratio: 273
movie_fb_likes: 0
color_binary: 0

In [206]:
movie_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4768 entries, 0 to 5042
Data columns (total 29 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   color                   4768 non-null   object
 1   director_name           4768 non-null   object
 2   num_critic_for_reviews  4768 non-null   float64
 3   duration                4768 non-null   float64
 4   director_fb_likes       4768 non-null   float64
 5   actor_3_fb_likes        4758 non-null   float64
 6   actor_2_name            4768 non-null   object
 7   actor_1_fb_likes        4768 non-null   float64
 8   gross                   4768 non-null   float64
 9   genres                  4768 non-null   object
 10  actor_1_name            4768 non-null   object
 11  movie_title             4768 non-null   object
 12  num_voted_users         4768 non-null   int64
 13  cast_total_fb_likes     4768 non-null   int64
 14  actor_3_name            4768 non-null   object
 15  facenumber_in_poster    4768 non-null   float64
 16  plot_keywords           4647 non-null   object
 17  movie_imdb_link         4768 non-null   object
 18  num_user_for_reviews    4768 non-null   float64
 19  language                4767 non-null   object
 20  country                 4768 non-null   object
 21  content_rating          4535 non-null   object
 22  budget                  4768 non-null   float64
 23  title_year              4768 non-null   float64
 24  actor_2_fb_likes        4765 non-null   float64
 25  imdb_score              4768 non-null   float64
 26  aspect_ratio            4495 non-null   float64
 27  movie_fb_likes          4768 non-null   int64
 28  color_binary            4768 non-null   int32
dtypes: float64(13), int32(1), int64(3), object(12)
memory usage: 1.1+ MB

correction genres

In [207]:
movie_data.genres

0       Action|Adventure|Fantasy|Sci-Fi
1              Action|Adventure|Fantasy
2             Action|Adventure|Thriller
3                       Action|Thriller
5               Action|Adventure|Sci-Fi
                     ...
5037                       Comedy|Drama
5038                       Comedy|Drama
5040              Drama|Horror|Thriller
5041               Comedy|Drama|Romance
5042                        Documentary
Name: genres, Length: 4768, dtype: object

In [208]:
# Split the 'genres' column into a list of genres for each row
genre_lists = movie_data['genres'].str.split('|')

# Determine the maximum number of genres in any row
max_num_genres = genre_lists.apply(len).max()

# Create new columns for genres dynamically
genre_columns = [f'genre{i}' for i in range(1, max_num_genres + 1)]
movie_data[genre_columns] = pd.DataFrame(genre_lists.tolist(), index=movie_data.index)

In [209]:
movie_data.head()

,color,director_name,num_critic_for_reviews,duration,director_fb_likes,actor_3_fb_likes,actor_2_name,actor_1_fb_likes,gross,genres,...,movie_fb_likes,color_binary,genre1,genre2,genre3,genre4,genre5,genre6,genre7,genre8
0,Color,James Cameron,723.00,178.00,0.00,855.00,Joel David Moore,1000.00,760505847.00,Action|Adventure|Fantasy|Sci-Fi,...,33000,1,Action,Adventure,Fantasy,Sci-Fi,None,None,None,None
1,Color,Gore Verbinski,302.00,169.00,563.00,1000.00,Orlando Bloom,40000.00,309404152.00,Action|Adventure|Fantasy,...,0,1,Action,Adventure,Fantasy,None,None,None,None,None
2,Color,Sam Mendes,602.00,148.00,0.00,161.00,Rory Kinnear,11000.00,200074175.00,Action|Adventure|Thriller,...,85000,1,Action,Adventure,Thriller,None,None,None,None,None
3,Color,Christopher Nolan,813.00,164.00,22000.00,23000.00,Christian Bale,27000.00,448130642.00,Action|Thriller,...,164000,1,Action,Thriller,None,None,None,None,None,None
5,Color,Andrew Stanton,462.00,132.00,475.00,530.00,Samantha Morton,640.00,73058679.00,Action|Adventure|Sci-Fi,...,24000,1,Action,Adventure,Sci-Fi,None,None,None,None,None

In [210]:
# Tu peux utiliser la fonction str.get_dummies() pour sÃ©parer les genres et crÃ©er des variables indicatrices
genres_dummies = movie_data['genres'].str.get_dummies(sep='|')

# Maintenant, tu peux concatÃ©ner ces variables indicatrices avec ton DataFrame original
movie_data = pd.concat([movie_data, genres_dummies], axis=1)



# Tu as maintenant un DataFrame avec des variables indicatrices pour les genres de films
print(movie_data.head())

   color      director_name  num_critic_for_reviews  duration  \
0  Color      James Cameron                  723.00    178.00
1  Color     Gore Verbinski                  302.00    169.00
2  Color         Sam Mendes                  602.00    148.00
3  Color  Christopher Nolan                  813.00    164.00
5  Color     Andrew Stanton                  462.00    132.00

   director_fb_likes  actor_3_fb_likes      actor_2_name  actor_1_fb_likes  \
0               0.00            855.00  Joel David Moore           1000.00
1             563.00           1000.00     Orlando Bloom          40000.00
2               0.00            161.00      Rory Kinnear          11000.00
3           22000.00          23000.00    Christian Bale          27000.00
5             475.00            530.00   Samantha Morton            640.00

         gross                           genres  ... Musical Mystery  News  \
0 760505847.00  Action|Adventure|Fantasy|Sci-Fi  ...       0       0     0
1 309404152.00         Action|Adventure|Fantasy  ...       0       0     0
2 200074175.00        Action|Adventure|Thriller  ...       0       0     0
3 448130642.00                  Action|Thriller  ...       0       0     0
5  73058679.00          Action|Adventure|Sci-Fi  ...       0       0     0

   Romance Sci-Fi  Short Sport Thriller  War Western
0        0      1      0     0        0    0       0
1        0      0      0     0        0    0       0
2        0      0      0     0        1    0       0
3        0      0      0     0        1    0       0
5        0      1      0     0        0    0       0

[5 rows x 61 columns]

In [211]:
movie_data.head()

,color,director_name,num_critic_for_reviews,duration,director_fb_likes,actor_3_fb_likes,actor_2_name,actor_1_fb_likes,gross,genres,...,Musical,Mystery,News,Romance,Sci-Fi,Short,Sport,Thriller,War,Western
0,Color,James Cameron,723.00,178.00,0.00,855.00,Joel David Moore,1000.00,760505847.00,Action|Adventure|Fantasy|Sci-Fi,...,0,0,0,0,1,0,0,0,0,0
1,Color,Gore Verbinski,302.00,169.00,563.00,1000.00,Orlando Bloom,40000.00,309404152.00,Action|Adventure|Fantasy,...,0,0,0,0,0,0,0,0,0,0
2,Color,Sam Mendes,602.00,148.00,0.00,161.00,Rory Kinnear,11000.00,200074175.00,Action|Adventure|Thriller,...,0,0,0,0,0,0,0,1,0,0
3,Color,Christopher Nolan,813.00,164.00,22000.00,23000.00,Christian Bale,27000.00,448130642.00,Action|Thriller,...,0,0,0,0,0,0,0,1,0,0
5,Color,Andrew Stanton,462.00,132.00,475.00,530.00,Samantha Morton,640.00,73058679.00,Action|Adventure|Sci-Fi,...,0,0,0,0,1,0,0,0,0,0

correction year

In [212]:
movie_data.title_year

0      2009.00
1      2007.00
2      2015.00
3      2012.00
5      2012.00
         ...
5037   2011.00
5038   2013.00
5040   2013.00
5041   2012.00
5042   2004.00
Name: title_year, Length: 4768, dtype: float64

In [213]:
# Convertir les valeurs de l'annÃ©e en chaÃ®nes de caractÃ¨res
movie_data['title_year'] = movie_data['title_year'].astype(str)

# Supprimer les dÃ©cimales et convertir en entiers
movie_data['title_year'] = movie_data['title_year'].str.split('.').str[0].astype(int)
movie_data['title_year']

0       2009
1       2007
2       2015
3       2012
5       2012
        ...
5037    2011
5038    2013
5040    2013
5041    2012
5042    2004
Name: title_year, Length: 4768, dtype: int32

In [214]:
# Enregistrer le DataFrame dans un nouveau fichier CSV
movie_data.to_csv('Datas/5000_movie_correction.csv', index=False)